# 配置详情请参考：https://docs.halo.run/zh/developer-guide/theme/config-files
genernal:
  label: 基本设置
  items:
    country:
      name: country
      label: 国家
      type: text
      default: ""
      placeholder: "国家信息"
      description: "国家信息将展示在页脚中，不填不展示（示例：中国）"
    province:
      name: province
      label: 省份
      type: text
      default: ""
      placeholder: "省份信息"
      description: "省份信息将展示在页脚中，不填不展示（示例：江西）"
    icp:
      name: icp
      label: ICP 备案号
      type: text
      default: ""
      placeholder: "请填写 ICP 备案号信息"
      description: "ICP 备案信息将展示在页脚中，不填不展示（示例：蜀ICP备xx号）"
    police:
      name: police
      label: 公网安备号
      type: text
      default: ""
      placeholder: "请填写公网安备号信息"
      description: "公网安备信息将展示在页脚中，不填不展示，一栏中单独关闭（示例：蜀公网安备xx号）"
    copyright:
      name: copyright
      label: 版权信息
      type: text
      default: ""
      placeholder: "版本信息"
      description: "版本信息将展示在页脚中，不填不展示（示例：Copyright@www.gloo.com.cn）"
    site_notice:
      name: site_notice
      label: 网站公告
      type: textarea
      placeholder: 请输入公告信息
      description: "网站公告信息，将展示在页面右侧，尽量简洁明了（不填不展示该模块，也可单独开关）"


aside:
  label: 侧边栏
  items:
    enable_aside:
      name: enable_aside
      label: 启用全局侧边栏
      type: switch
      data-type: bool
      default: true
      description: "是否启用侧边栏（全局），关闭后所有页面都没有侧边栏（优先级高于页面元数据）"
      options:
        - value: true
          label: 是
        - value: false
          label: 否
    aside_position:
      name: aside_position
      label: 侧边栏位置
      type: radio
      data-type: text
      default: right
      description: "侧边栏展示位置，左边或右边"
      options:
        - value: left
          label: 左侧
        - value: right
          label: 右侧
    site_btn:
      name: site_btn
      label: 信息按钮
      type: textarea
      placeholder: 请输入
      default: "关注我||/"
      description: "侧边栏按钮信息请按照格式填写否则报错  跳转文字|跳转url"
    enable_newest_post:
      name: enable_newest_post
      label: 展示最新文章
      type: switch
      data-type: bool
      default: true
      description: "在右侧展示最新文章"
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    newest_page_size:
      name: newest_page_size
      label: 最新文章条数
      default: 5
      description: "右侧最新文章展示条数，填写数字即可，默认展示最新的5篇文章（需开启最新文章）"
    #    show_newreply:
    #      name: show_newreply
    #      label: 展示最新评论
    #      type: switch
    #      data-type: bool
    #      default: true
    #      description: "在右侧展示最新的评论"
    #      options:
    #        - value: true
    #          label: 开启
    #        - value: false
    #          label: 关闭
    #    newreply_page_size:
    #      name: newreply_page_size
    #      label: 最新评论条数
    #      type: text
    #      data-type: long
    #      default: 5
    #      description: "右侧最新评论展示条数，填写数字即可，默认展示最新的5条评论（需开启最新评论）"
    enable_notice:
      name: enable_notice
      label: 展示网站公告
      type: switch
      data-type: bool
      default: true
      description: "在右侧展示公告信息模块，必须配置公告内容才生效（请在 '基本设置' 栏中配置）"
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    enable_categories:
      name: enable_categories
      label: 侧边栏展示分类
      type: switch
      data-type: bool
      default: true
      description: "在右侧展示分类"
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    enable_tags:
      name: enable_tags
      label: 侧边栏展示标签
      type: switch
      data-type: bool
      default: true
      description: "在右侧展示标签"
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭


index:
  label: 首页
  items:
    qrcode_qq:
      name: qrcode_qq
      label: "QQ二维码"
      type: attachment
      default: ""
      placeholder: "QQ加好友二维码，不填不显示"
    qrcode_wx:
      name: qrcode_qq
      label: "微信二维码"
      type: attachment
      default: ""
      placeholder: "微信加好友二维码，不填不显示"
    post_thumbnail:
      name: post_thumbnail
      label: 文章默认缩略图
      width: 100%
      type: attachment
      default: "https://picsum.photos/id/1081/210/140"
      description: "文章无配图时生效，可使用占位图服务（210*140）"
    provide_data:
      name: provide_data
      label: 手动配置数据
      type: textarea
      default: "欢迎使用Joe2.0主题-|||-https://bbchin.com/themes/joe2.0/source/images/dp/welcome.jpg=====欢迎使用Joe2.0主题-|||-https://bbchin.com/themes/joe2.0/source/images/dp/welcome.jpg=====欢迎使用Joe2.0主题-|||-https://bbchin.com/themes/joe2.0/source/images/dp/welcome.jpg=====欢迎使用Joe2.0主题-|||-https://bbchin.com/themes/joe2.0/source/images/dp/welcome.jpg=====欢迎使用Joe2.0主题-|||-https://bbchin.com/themes/joe2.0/source/images/dp/welcome.jpg=====欢迎使用Joe2.0主题-|||-https://bbchin.com/themes/joe2.0/source/images/dp/welcome.jpg====="
      description: "手动配置首页的提供服务数据，仅当数据来源为 “手动配置” 时生效（注意：主题内默认配置了演示数据）。【多个数据之间用 '=====' 隔开，属性之间用 '-|||-' 隔开】(为了美观，允许换行)，【具体示例】标题-|||-描述-|||-跳转链接，不需要跳转写 '#' 即可（请严格按照此格式或默认示例进行配置，否则可能导致网站崩溃）"


about:
  label: 关于我
  items:
    keyword_data:
      name: keyword_data
      label: 手动配置数据
      type: textarea
      default: "欢迎使用Joe2.0主题-|||-https://bbchin.com/themes/joe2.0/source/images/dp/welcome.jpg-|||-https://github.com/qinhua/halo-theme-joe2.0#readme=====剪映创作不凡 - TRACK概念片-|||-https://img.zcool.cn/community/011ca2614d755911013e894390b399.png@1280w_1l_2o_100sh.png-|||-#"
      description: "手动配置首页的提供服务数据，仅当数据来源为 “手动配置” 时生效（注意：主题内默认配置了演示数据）。【多个数据之间用 '=====' 隔开，属性之间用 '-|||-' 隔开】(为了美观，允许换行)，【具体示例】标题-|||-描述-|||-跳转链接，不需要跳转写 '#' 即可（请严格按照此格式或默认示例进行配置，否则可能导致网站崩溃）"
    skill_data:
      name: skill_data
      label: 手动配置数据
      type: textarea
      default: "欢迎使用Joe2.0主题-|||-https://bbchin.com/themes/joe2.0/source/images/dp/welcome.jpg-|||-https://github.com/qinhua/halo-theme-joe2.0#readme=====剪映创作不凡 - TRACK概念片-|||-https://img.zcool.cn/community/011ca2614d755911013e894390b399.png@1280w_1l_2o_100sh.png-|||-#"
      description: "手动配置首页的提供服务数据，仅当数据来源为 “手动配置” 时生效（注意：主题内默认配置了演示数据）。【多个数据之间用 '=====' 隔开，属性之间用 '-|||-' 隔开】(为了美观，允许换行)，【具体示例】标题-|||-描述-|||-跳转链接，不需要跳转写 '#' 即可（请严格按照此格式或默认示例进行配置，否则可能导致网站崩溃）"
    

archives:
  label: 归档
  items:
    archives_title:
      name: archives_title
      label: 归档页标题
      default: "文章归档"
      placeholder: "请输入"
      description: "修改归档标题"
    enable_top_archives_background_img:
      name: enable_top_archives_background_img
      label: 开启顶部背景图
      type: switch
      data-type: bool
      default: true
      placeholder: "开启顶部背景图"
      options:
        - value: true
          label: 是
        - value: false
          label: 否
    top_archives_background_img:
      name: top_archives_background_img
      label: 顶部背景图
      type: attachment
      default: "https://gitee.com/dhjdd/Timo/raw/master/1642841299688.png"
      placeholder: "顶部背景图"
    enable_archives_aside:
      name: enable_archives_aside
      label: 是否展示侧边栏
      type: switch
      data-type: bool
      default: true
      description: "是否展示侧边栏"
      options:
        - value: true
          label: 是
        - value: false
          label: 否

categories:
  label: 分类
  items:
    categories_title:
      name: categories_title
      label: 分类页标题
      default: "全部分类"
      placeholder: "请输入"
      description: "修改分类页顶部的标题"


links:
  label: 友链
  items:
    links_title:
      name: links_title
      label: 友链页标题
      default: "友情链接"
      placeholder: "请输入"
      description: "修改友链页顶部展示的标题"
    enable_top_links_background_img:
      name: enable_top_links_background_img
      label: 开启顶部背景图
      type: switch
      data-type: bool
      default: true
      placeholder: "开启顶部背景图"
      options:
        - value: true
          label: 是
        - value: false
          label: 否
    top_links_background_img:
      name: top_links_background_img
      label: 顶部背景图（友链）
      type: attachment
      default: "https://gitee.com/dhjdd/Timo/raw/master/1642841299688.png"
      placeholder: "顶部背景图（友链）"
    enable_links_aside:
      name: enable_links_aside
      label: 是否展示侧边栏
      type: switch
      data-type: bool
      default: true
      description: "是否展示侧边栏"
      options:
        - value: true
          label: 是
        - value: false
          label: 否


journals:
  label: 日志
  items:
    journals_title:
      name: journals_title
      label: 日志页标题
      default: "我的动态"
      placeholder: "请输入"
      description: "修改日志页顶部展示的标题"
    enable_top_journals_background_img:
      name: enable_top_journals_background_img
      label: 开启顶部背景图
      type: switch
      data-type: bool
      default: true
      placeholder: "开启顶部背景图"
      options:
        - value: true
          label: 是
        - value: false
          label: 否
    top_journals_background_img:
      name: top_journals_background_img
      label: 顶部背景图
      type: attachment
      default: "https://gitee.com/dhjdd/Timo/raw/master/1642841299688.png"
      placeholder: "顶部背景图"
    enable_journals_aside:
      name: enable_journals_aside
      label: 是否展示侧边栏
      type: switch
      data-type: bool
      default: true
      description: "是否展示侧边栏"
      options:
        - value: true
          label: 是
        - value: false
          label: 否


sheet:
  label: 自定义
  items:
    enable_top_sheet_background_img:
      name: enable_top_sheet_background_img
      label: 开启顶部背景图
      type: switch
      data-type: bool
      default: true
      placeholder: "开启顶部背景图"
      options:
        - value: true
          label: 是
        - value: false
          label: 否
    top_sheet_background_img:
      name: top_sheet_background_img
      label: 顶部背景图
      type: attachment
      default: "https://gitee.com/dhjdd/Timo/raw/master/1642841299688.png"
      placeholder: "顶部背景图"


code_block:
  label: 代码块
  items:
    #    enable_code_copy:
    #      name: enable_code_copy
    #      label: 代码复制
    #      type: switch
    #      data-type: bool
    #      default: true
    #      description: 开启代码块复制按钮
    #      options:
    #        - value: true
    #          label: 开启
    #        - value: false
    #          label: 关闭
    #    enable_code_expander:
    #      name: enable_code_expander
    #      label: 代码折叠
    #      type: switch
    #      data-type: bool
    #      default: false
    #      description: "开启代码块折叠功能"
    #      options:
    #        - value: true
    #          label: 开启
    #        - value: false
    #          label: 关闭
    #    fold_long_code:
    #      name: fold_long_code
    #      label: 自动折叠长代码块
    #      type: switch
    #      data-type: bool
    #      default: false
    #      description: "自动折叠 <文章页> 中内容很长的代码块，提高阅读效率，此操作会出现布局偏移，可能带来一些滚动相关问题，如无必要不建议开启（必须先开启“代码折叠”选项，否则无效）"
    #      options:
    #        - value: true
    #          label: 开启
    #        - value: false
    #          label: 关闭
    #    long_code_height:
    #      name: long_code_height
    #      label: 自动折叠的高度
    #      type: text
    #      data-type: long
    #      default: 800
    #      placeholder: "请输入数字"
    #      description: "触发长代码块自动折叠的高度（单位px），只填数字即可（默认800），填 0 将折叠所有代码块"
    code_theme:
      name: code_theme
      label: 代码主题
      type: select
      data-type: string
      default: "one-dark"
      description: "设置代码块主题，可通过后台元数据为每篇文章设置单独的代码主题，主题来自 prism-themes，见https://github.com/PrismJS/prism-themes"
      options:
        - value: "one-dark"
          label: "one-dark"
        - value: "one-light"
          label: "one-light"
        - value: "a11y-dark"
          label: "a11y-dark"
        - value: "atom-dark"
          label: "atom-dark"
        - value: "base16-ateliersulphurpool.light"
          label: "base16-ateliersulphurpool.light"
        - value: "cb"
          label: "cb"
        - value: "coldark-cold"
          label: "coldark-cold"
        - value: "coldark-dark"
          label: "coldark-dark"
        - value: "coy-without-shadows"
          label: "coy-without-shadows"
        - value: "darcula"
          label: "darcula"
        - value: "dracula"
          label: "dracula"
        - value: "duotone-dark"
          label: "duotone-dark"
        - value: "duotone-earth"
          label: "duotone-earth"
        - value: "duotone-forest"
          label: "duotone-forest"
        - value: "duotone-light"
          label: "duotone-light"
        - value: "duotone-sea"
          label: "duotone-sea"
        - value: "duotone-space"
          label: "duotone-space"
        - value: "ghcolors"
          label: "ghcolors"
        - value: "gruvbox-dark"
          label: "gruvbox-dark"
        - value: "gruvbox-light"
          label: "gruvbox-light"
        - value: "holi-theme"
          label: "holi-theme"
        - value: "hopscotch"
          label: "hopscotch"
        - value: "lucario"
          label: "lucario"
        - value: "material-dark"
          label: "material-dark"
        - value: "material-light"
          label: "material-light"
        - value: "material-oceanic"
          label: "material-oceanic"
        - value: "night-owl"
          label: "night-owl"
        - value: "nord"
          label: "nord"
        - value: "pojoaque"
          label: "pojoaque"
        - value: "shades-of-purple"
          label: "shades-of-purple"
        - value: "solarized-dark-atom"
          label: "solarized-dark-atom"
        - value: "synthwave84"
          label: "synthwave84"
        - value: "vs"
          label: "vs"
        - value: "vsc-dark-plus"
          label: "vsc-dark-plus"
        - value: "xonokai"
          label: "xonokai"
        - value: "z-touch"
          label: "z-touch"


post:
  label: 文章
  items:
    enable_post_aside:
      name: enable_post_aside
      label: 是否展示侧边栏
      type: switch
      data-type: bool
      default: true
      description: "是否展示侧边栏"
      options:
        - value: true
          label: 是
        - value: false
          label: 否
    enable_top_post_background_img:
      name: enable_top_post_background_img
      label: 开启顶部背景图
      type: switch
      data-type: bool
      default: true
      placeholder: "开启顶部背景图"
      options:
        - value: true
          label: 是
        - value: false
          label: 否
    #    enable_aside_expander:
    #      name: enable_aside_expander
    #      label: 展示侧边栏切换按钮
    #      type: switch
    #      data-type: bool
    #      default: true
    #      description: "文章页顶部显示用于切换侧边栏显示/隐藏状态的按钮（仅在展示侧边栏情况下生效）"
    #      options:
    #        - value: true
    #          label: 是
    #        - value: false
    #          label: 否
    enable_donate:
      name: enable_donate
      label: 开启打赏
      type: switch
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    qrcode_zfb:
      name: qrcode_zfb
      label: "支付宝二维码"
      type: attachment
      default: ""
      placeholder: "打赏用的支付宝收款二维码链接，不填不显示"
    qrcode_wx:
      name: qrcode_wx_pay
      label: "微信二维码"
      type: attachment
      default: ""
      placeholder: "打赏用的微信收款二维码链接，不填不显示"


social:
  label: 社交
  items:
    email:
      name: email
      label: 邮箱
      type: text
      default: ""
      placeholder: "邮箱地址"
    telphone:
      name: telphone
      label: 电话号码
      type: text
      default: ""
      placeholder: "电话号码"
    github:
      name: github
      label: Github
      type: text
      default: ""
      placeholder: "github主页地址"
    zhihu:
      name: zhihu
      label: 知乎
      type: text
      default: ""
      placeholder: "知乎主页地址"
